# Generated by Django 3.0.7 on 2020-06-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COVIDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=100)),
                ('total_cases', models.IntegerField(default='')),
                ('new_cases', models.IntegerField(blank=True, default='', null=True)),
                ('total_deaths', models.IntegerField(default='')),
                ('new_deaths', models.IntegerField(blank=True, default='', null=True)),
                ('total_recovered', models.IntegerField(default='')),
                ('active_cases', models.IntegerField(default='')),
                ('day', models.DateField(default='')),
            ],
        ),
    ]
